### ISSUE TITLE
LIL matrix: storage

### ISSUE THREAD

**Issue by tdegeus** [xtensor-stack/xtensor-sparse#5] opened 2020-04-04 17:15 UTC
First of all: thanks @gouarin for the initiative! 

I was just reading the code and came across something that I don't understand. How is `m_data` allocated / resized? Also, is the current stored not simply a dense matrix?

**Comment by gouarin** [comment] 2020-04-04 17:35
@tdegeus thanks!

It's the first attempt and we already see with @JohanMabille some implementation issues.
But `m_data` is a map so you don't have to allocate memory. You just have to insert key and value.
So you have a sparse matrix where the non zeros are defined by the keys.

The problem is that we want a similar implementation of xtensor. Then we want to be able to reshape, for example. But is it possible? What does it mean?

We will open several issues to open the discussion and to find the best implementations.

**Comment by tdegeus** [comment] 2020-04-05 09:45
OK! From my side I would be happy to contribute with a CRS and COO implementation (did it two times before in private libraries). I presume that it is most efficient that I wait for the issues to respond to them or create PRs?

**Comment by tdegeus** [comment] 2020-04-05 09:48
A small comment up-front. It would be nice to quite soon have a way to cast to a dense `xarray` or `xtensor`, to be able to test new sparse methods against existing dense methods.

**Comment by gouarin** [comment] 2020-04-05 17:01
@tdegeus feel free to open a new issue for each data structure and explain what implementation you need for your test case.

Note that we try to have an ND implementation.

For the dense array, the assign process used by xtensor should work if you assign a sparse array into a xarray or a xtensor. We just have to write it ;).

**Comment by JohanMabille** [comment] 2020-04-08 13:38
Closing this since we now have `xmap_array` and `xmap_tensor` classes.

**Closed as completed by JohanMabille** 2020-04-08 13:38 UTC
